-- SNUSDEX MySQL Database Structure

CREATE DATABASE IF NOT EXISTS snusdex;
USE snusdex;

-- TABLES
CREATE TABLE IF NOT EXISTS `Brand`(
    BrandID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (BrandID),
    UNIQUE KEY (Name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Type`(
    TypeID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TypeDesc VARCHAR(25) NOT NULL,
    PRIMARY KEY (TypeID),
    UNIQUE KEY (TypeDesc)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BagType`(
    BagTypeID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    BagTypeDesc VARCHAR(25) NOT NULL,
    PRIMARY KEY (BagTypeID),
    UNIQUE KEY (BagTypeDesc)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Strength`(
    StrengthID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    StrengthDesc VARCHAR(25) NOT NULL,
    PRIMARY KEY (StrengthID),
    UNIQUE KEY (StrengthDesc)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Company`(
    CompanyID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    CompDesc TEXT,
    PRIMARY KEY (CompanyID),
    UNIQUE KEY (Name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Product`(
    ProdID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    TypeID SMALLINT UNSIGNED,
    BagTypeID SMALLINT UNSIGNED,
    BrandID SMALLINT UNSIGNED,
    StrengthID SMALLINT UNSIGNED,
    Nicotine DOUBLE(10, 2),
    Weight DOUBLE(10, 2),
    NumBags TINYINT(3),
    Image TEXT,
    PRIMARY KEY (ProdID),
    UNIQUE KEY (Name),

    FOREIGN KEY (TypeID)
    REFERENCES Type (TypeID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

    FOREIGN KEY (BagTypeID)
    REFERENCES BagType (BagTypeID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

    FOREIGN KEY (BrandID)
    REFERENCES Brand (BrandID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

    FOREIGN KEY (StrengthID)
    REFERENCES Strength (StrengthID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB;

